### ISSUE TITLE
Control and Wifi Loosing 

### ISSUE THREAD

**Issue by Pat2405Rick** [ttimpe/homebridge-midea#16]
Hey,

first: Thank you very mutch for developing this Plugin!

Ive got an Dimstal Golden Fin Split AC (Europe), it comes with an Nethome Plus USB Wifi dongle.

Installation in Midea and/or Nethome Plus App works!

Plugin configuration works.
Temperatures are correct and controlling via the Home App work. But only for 1-2 min...
After the first few Control Actions the AC does not recognize anymore.

Homebridge still running and connection between Home App and Homebridge is still running.

Switching back to the Midea App I see the AC is Offline.
No more options to restore anything. Only way from this point is:
Deleting the AC in Midea App
Connect as new device
After that of course the same problems start again...

Ive tried many times...

Thanks in Advantage!

sorry for my bad English ;)

**Comment by ttimpe** [comment]
Hello Patrick,

as I do not have that specific model of AC unit, I am unable to verify your issue. I do however sometimes encounter sudden hang-ups of the unit as well. These have not been as severe as you are describing. I have never had the unit not respond in any first-party app.

For further troubleshooting of these kinds of issues, we will need a way to debug the Midea API, preferably by having actual documentation. I do plan on reaching out to them about this ASAP.
