### ISSUE TITLE
Schedules support 

### ISSUE THREAD

**Issue by idanb7** [ttimpe/homebridge-midea#26]
Hi,
Great work!
just a quick question, any chance of having the schedules supported?
is it an API issue? or maybe doesn't support on homebridge/homekit?
Thx,
Idan

**Comment by ttimpe** [comment]
Are you talking about schedules defined in the Midea app?

**Comment by idanb7** [comment]
Yes

**Comment by ttimpe** [comment]
In what way do you want the schedules to be supported? You can just create scenes and automations in the Home app.

**Comment by idanb7** [comment]
The same way u can define in the app. 
Example-
On Sunday I want on at 8pm and off at 9pm

**Comment by ttimpe** [comment]
This can be done using Home automations already.
