### ISSUE TITLE
The issue of local vs cloud connectivity

### ISSUE THREAD

**Issue by ttimpe** [ttimpe/homebridge-midea#5]
Hello everyone,

As some of you may have read in both of the issues relating to the recent short outage of the Midea cloud service, it has been requested that the plugin should work via a local connection to the AC.

My initial idea for this plugin was to eventually convert it to Platform capable of controlling all devices in one‘s Midea account.

As I currently only have one Midea AC unit and, for the foreseeable future, don‘t plan on getting a second one, making this plugin only communicate over the local network wouldn‘t be an issue for me, however it would involve direct socket communication.

In your opinion, what is more important: A platform with all devices from one‘s account or local control, with potentially multiple instances of this plugin in one Homebridge installation?

**Comment by slydlake** [comment]
Hi @ttimpe 
My AC unfortunately does not support local connection and I have only one device.
So for me it is more higher priority has the multiple device solution. But I have no plans at the moment to buy a second one 😉

**Comment by thoorn** [comment]
@ttimpe First of all thanks a lot for this homebridge plug-in! My AC also lacks support for a local connection (Comfee MSR23-09HRDN1-QE, which is also compatible with Midea), so for me the platform solution works best.

I saw you have future plans to also control the fan speed and swing mode, that would make the plug-in indeed even better! Good work.

**Comment by ttimpe** [comment]
I am leaning towards building a platform to query all devices in the account. Maybe I‘ll look into this in the coming days.

**Comment by ttimpe** [comment]
So I was bored and a version of this plugin as a dynamic platform in TypeScript is now in the development branch. I undid the merge request in because of the swing mode and fan settings being in the config.json

**Comment by ttimpe** [comment]
**Please test the current version in the development branch and provide feedback.**
I'm currently wondering how I will handle the upgrade from an Accessory to a Platform. Would registering a MigrationHelper accessory and using that to just rewrite the config.json be an option?

**Comment by ttimpe** [comment]
Closing for now as the plugin has been converted to a platform. Local network support may be added in the future once proper documentation is available. Please feel free to open a pull request if you have a working  implementation.
